version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminPassword
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb/data/db:/data/db
      - ~/mongodb/data/configdb:/data/configdb
