import { Types } from 'mongoose';
import { CustomerDocument } from '../../src/customers/schemas/customer.schema';

export const mockCustomer: Partial<CustomerDocument> = {
  _id: new Types.ObjectId('668ff65d0f0dea7b199341c2'),
  username: 'john_doe',
  password: 'hashed_password_1',
  firstName: 'John',
  lastName: 'Doe',
  email: 'john@example.com',
  phoneNumber: '1234567890',
  profilePicture: '',
  bio: 'Experienced hairdresser',
  location: 'New York, USA',
  preferredHairdresserId: '',
  servicesInterestedIn: ['cut', 'color', 'style'],
  bookingHistory: [],
  reviews: [],
  ratings: [5, 4, 5],
  isVerified: true,
  createdAt: new Date('2024-07-11T15:12:29.669Z'),
  updatedAt: new Date('2024-07-11T15:12:29.669Z'),
  toObject: jest.fn().mockReturnValue({
    _id: new Types.ObjectId('668ff65d0f0dea7b199341c2'),
    username: 'john_doe',
    password: undefined,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@example.com',
    phoneNumber: '1234567890',
    profilePicture: '',
    bio: 'Experienced hairdresser',
    location: 'New York, USA',
    preferredHairdresserId: '',
    servicesInterestedIn: ['cut', 'color', 'style'],
    bookingHistory: [],
    reviews: [],
    ratings: [5, 4, 5],
    isVerified: true,
    createdAt: new Date('2024-07-11T15:12:29.669Z'),
    updatedAt: new Date('2024-07-11T15:12:29.669Z'),
  }),
  toJSON: jest.fn().mockReturnValue({
    _id: new Types.ObjectId('668ff65d0f0dea7b199341c2'),
    username: 'john_doe',
    password: undefined,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@example.com',
    phoneNumber: '1234567890',
    profilePicture: '',
    bio: 'Experienced hairdresser',
    location: 'New York, USA',
    preferredHairdresserId: '',
    servicesInterestedIn: ['cut', 'color', 'style'],
    bookingHistory: [],
    reviews: [],
    ratings: [5, 4, 5],
    isVerified: true,
    createdAt: new Date('2024-07-11T15:12:29.669Z'),
    updatedAt: new Date('2024-07-11T15:12:29.669Z'),
  }),
};
